apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: HEAD
    chart: harbor
    helm: 
      values: |
        expose.ingress.hosts.core: harbor.127-0-0-1.nip.io

  syncPolicy:
    automated:
      prune: true
