apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: x
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
