apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: x
    chart: kibana
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
