apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.0.1
    chart: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
