apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: gitops
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: x
  syncPolicy:
    syncOptions:
    - CreateNamespace=true