apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.16.2
    chart: mysql
    helm:
      parameters:
        - name: auth.rootPassword
          value: secretpassword
        - name: auth.database 
          value: app_database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true