apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 1.6.10
    chart: mysql
    helm:
      values: |
        - auth.rootPassword: secretpassword
        - auth.database: app_database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true