apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: x
    chart: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
